import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

export const SOURCE_FILES = ["config.js", "image.js", "html-entities.js", "markdown.js", "api.js", "ocr.js"];

export async function composePluginSource(root) {
  const parts = await Promise.all(SOURCE_FILES.map(async (name) => {
    const source = await readFile(resolve(root, "src", name), "utf8");
    return `// src/${name}\n${source.replace(/\r\n?/g, "\n").trimEnd()}\n`;
  }));
  return "// Generated by scripts/build-source.mjs. Edit src/*.js, then rebuild.\n\n" + parts.join("\n");
}
